### ISSUE TITLE
Button gradients no longer work with Firefox

### ISSUE THREAD

**Issue by nwilliams** [NuGet/NuGetGallery#2114]
With the latest version of Firefox (29.0), the button gradients are no longer rendering correctly. For example, the 'Install NuGet' button on the home page and the 'Register/Sign In' buttons on the account page are now flat in appearance.
### Before

![nugetbuttonsbefore](https://cloud.githubusercontent.com/assets/204802/2907659/f4fb7eca-d61e-11e3-92e9-042567959e83.png)
### After

![nugetbuttonsafter](https://cloud.githubusercontent.com/assets/204802/2907670/139841e2-d61f-11e3-88c9-f0bb76726030.png)
### CSS from the Firefox Inspector

``` css
.featured div a.install:hover {
    background-color: #376783;
    border-color: #4585AA;
    text-decoration: none;
}
.featured div a.install {
    background-color: #4585AA;
    border: 1px solid #376783;
    border-radius: 4px;
    box-shadow: 0px 0px 1px #FFF inset, 1px 1px 1px rgba(0, 0, 0, 0.3);
    color: #FFF;
    display: block;
    font-size: 2em;
    line-height: 2em;
    margin-top: 25px;
    text-align: center;
    width: 95%;
}
```
