### ISSUE TITLE
[Azure Search] Run functional tests from Azure Search service deployment

### ISSUE THREAD

**Issue by loic-sharma** [NuGet/NuGetGallery#6963]
This is _in additional_ to E2E tests (tracked separately). We need to check each Azure Search endpoint so that it is meeting protocol. We can start with a single very silly functional test that just makes sure that "/" returns `{"Success":true}`.

Steps:

1. Bring https://nuget.visualstudio.com/NuGetBuild/_build?definitionId=112 up to par so it can run functional tests against a given environment.
1. Queue this test run during Azure Search service deployment much like what we do for legacy search service or gallery deployments.
1. Swap staging slot _after_ tests succeed.

Related issues:
1. V2 search functional tests: https://github.com/NuGet/NuGetGallery/issues/7233
1. V3 search functional tests: https://github.com/nuget/nugetgallery/issues/2798
1. Autocomplete functional tests : https://github.com/NuGet/NuGetGallery/issues/7232
1. E2E during deployment: https://github.com/NuGet/NuGetGallery/issues/7228

Currently, Azure Search's functional tests are run by a fork of NuGet.Services.Metadata's functional tests. Possible steps needed to bring it up to snuff include:

* [ ] Add the `NuGetBuildBranch` variable with value `master`
* [ ] Add the `ConfigurationName` variable with value `Dev-USNC`. This should be settable at queue time
* [ ] Update `Phase 1` to enable `Allow scripts to access the OAuth token`
* [ ] Add a new build step `Import configuration` with the following YAML:

```YAML
steps:
- task: PowerShell@1
  displayName: 'Import configuration'
  inputs:
    scriptName: '$(Build.SourcesDirectory)\tests\Scripts\Import-Configuration.ps1'
    arguments: '-Instance "nuget" -Project "NuGetBuild" -PersonalAccessToken $(System.AccessToken) -Repository "NuGetBuild" -Branch "$(NuGetBuildBranch)" -ConfigurationName "$(ConfigurationName)"'
```
